name: hgw
description: Flutter HGW
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

  pdf: ^3.10.0
  printing: ^5.11.0
  intl: ^0.19.0

  # Networking
  http: ^1.5.0
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0
  file_selector: ^1.0.3
  file_selector_macos: ^0.9.4+4

  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  youtube_player_flutter: ^8.1.0

  cupertino_icons: ^1.0.6

  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true